import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@components/navbar";
import Notification from "@components/Notification";
import AuthSession from "./components/AuthSession";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthSession>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className}>
         
          {children}
          <Notification />
        </body>
      </html>
    </AuthSession>
  );
}
